site_name: Project Documentation
site_description: Comprehensive documentation for public APIs, functions, and components
site_url: https://example.com
repo_url: https://example.com/repo
repo_name: Repository

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - content.tabs.link

nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Usage: usage.md
  - API Reference:
      - Overview: api/README.md
      - JavaScript/TypeScript: api/javascript.md
      - Python: api/python.md
  - Components: components.md
  - Examples: examples.md
  - FAQ: faq.md
  - Contributing: contributing.md
  - Changelog: changelog.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - tables

plugins:
  - search